#!/usr/bin/env python3
"""Reproduce the always-available Latin bitmap subset from the bundled Unifont."""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[1]
FIRST, LAST = 0xC0, 0x17F


def render():
    blob = (ROOT / "docs/unifont.bin").read_bytes()
    if blob[:4] not in (b"AUF1", b"AUF2"):
        raise ValueError("not an AUF font")
    rows = []
    for cp in range(FIRST, LAST + 1):
        record = blob[4 + cp * 33:4 + (cp + 1) * 33]
        if len(record) != 33 or record[0] != 1 or any(record[17:]):
            raise ValueError(f"U+{cp:04X} is not a halfwidth glyph")
        rows.append("    {" + ", ".join(f"0x{byte:02x}" for byte in record[1:17]) + f"}}, // U+{cp:04X}")
    return '''// Generated by scripts/mklatinfont.py; do not hand-edit the bitmap table.
// GNU Unifont (c) Roman Czyborra and Unifont contributors.
// GPLv2+ with the font-embedding exception; https://unifoundry.com/unifont/
// Subset of docs/unifont.bin, SHA256: HASH
#include "AdvLatinFont.h"
#include <cstring>

namespace advui
{
namespace
{
// Constant flash data: no SD mount, allocation, or runtime cache.
const uint8_t kLatin[192][16] = {
ROWS
};
}

int latinGlyphWidth(uint32_t cp)
{
    return cp >= 0xC0 && cp <= 0x17F ? 8 : 0;
}

int latinGlyph(uint32_t cp, uint8_t *out)
{
    if (!out || !latinGlyphWidth(cp))
        return 0;
    memcpy(out, kLatin[cp - 0xC0], 16);
    return 8;
}
} // namespace advui
'''.replace("HASH", hashlib.sha256(blob).hexdigest()).replace("ROWS", "\n".join(rows))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the checked-in generated source")
    args = parser.parse_args()
    generated = render()
    if args.check:
        actual = (ROOT / "overlay/src/advui/AdvLatinFont.cpp").read_text()
        if actual != generated:
            raise SystemExit("Latin font source differs from bundled Unifont; regenerate with mklatinfont.py")
        print("Embedded Latin glyph provenance: OK")
    else:
        print(generated, end="")
