#!/usr/bin/env bash
# Copy the additive overlay into the pinned upstream firmware submodule before building.
#
# The submodule commit stays pinned to upstream meshtastic/firmware. Our code
# lives in overlay/; this script copies it in and applies a small idempotent
# integration patch set to the build worktree.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FW="$ROOT/firmware"

# Preserve mtimes for unchanged files so an ordinary sync does not turn the
# next PlatformIO invocation into a three-minute full rebuild. Minimal systems
# without rsync keep the old, correct full-copy fallback.
if command -v rsync >/dev/null 2>&1; then
  mkdir -p "$FW/src/advui"
  rsync -a --delete --exclude AdvVersion.h "$ROOT/overlay/src/advui/" "$FW/src/advui/"
else
  rm -rf "$FW/src/advui"
  cp -R "$ROOT/overlay/src/advui" "$FW/src/advui"
fi

# The advui release version, baked in for the splash: the pushed tag in CI,
# git-describe locally (falls back to "dev" outside a git checkout).
ADV_VER="${GITHUB_REF_NAME:-}"
case "$ADV_VER" in
  v[0-9]*) ;;
  *) ADV_VER="$(git -C "$ROOT" describe --tags --always 2>/dev/null || echo dev)" ;;
esac
ADV_VERSION_TMP="$(mktemp)"
cat > "$ADV_VERSION_TMP" <<EOF
// Generated by sync-overlay.sh — not part of the repo.
#pragma once
#define ADVUI_VERSION "$ADV_VER"
EOF
if [ ! -f "$FW/src/advui/AdvVersion.h" ] || ! cmp -s "$ADV_VERSION_TMP" "$FW/src/advui/AdvVersion.h"; then
  mv "$ADV_VERSION_TMP" "$FW/src/advui/AdvVersion.h"
else
  rm -f "$ADV_VERSION_TMP"
fi

if command -v rsync >/dev/null 2>&1; then
  mkdir -p "$FW/variants/esp32s3/m5stack_cardputer_adv_advui"
  rsync -a --delete "$ROOT/overlay/variants/esp32s3/m5stack_cardputer_adv_advui/" \
        "$FW/variants/esp32s3/m5stack_cardputer_adv_advui/"
else
  rm -rf "$FW/variants/esp32s3/m5stack_cardputer_adv_advui"
  cp -R "$ROOT/overlay/variants/esp32s3/m5stack_cardputer_adv_advui" \
        "$FW/variants/esp32s3/m5stack_cardputer_adv_advui"
fi

# The 2.7 release line enables NimBLE central/observer, six controller
# activities and C++ exceptions in its global sdkconfig.defaults. The newer
# pioarduino line exposes an esp32s3_base.custom_sdkconfig list that our child
# environment must extend. Do not interpolate that newer option on 2.7: plain
# PlatformIO correctly rejects references to options that do not exist.
ADV_PIO="$FW/variants/esp32s3/m5stack_cardputer_adv_advui/platformio.ini"
if ! grep -q '^custom_sdkconfig[[:space:]]*=' "$FW/variants/esp32s3/esp32s3.ini"; then
  perl -0pi -e 's{\ncustom_sdkconfig =\n.*?\nlib_deps =}{\n; Meshtastic 2.7 supplies the required BLE roles and exceptions in sdkconfig.defaults.\nlib_deps =}s' "$ADV_PIO"
fi

# main.cpp: three idempotent injections —
#  1. include our UI header,
#  2. create the UI once after setupModules() (engine + nodeDB up); AdvUI is an
#     OSThread and then schedules itself, so there is no main-loop edit,
#  3. make the USB-CDC console effectively non-blocking, so boot logging doesn't stall for
#     seconds when the port is enumerated by a host that isn't draining it
#     (Arduino-ESP32 2.0.17 underflows an internal retry counter at exactly 0,
#     so the minimum safe timeout is 1 ms).
MC="$FW/src/main.cpp"
# Meshtastic 2.7 declares this definition as OSThread*, while the module
# headers declare the same symbol as AmbientLightingThread*. That is an ODR
# violation under LTO (and the linker warns that it may misoptimise callers).
# The object constructed into the pointer is always AmbientLightingThread, so
# make the definition match its declarations. Newer upstreams that already
# agree need no patch.
if [ -f "$MC" ] && grep -q '^OSThread \*ambientLightingThread;$' "$MC"; then
  perl -0pi -e 's{^OSThread \*ambientLightingThread;$}{AmbientLightingThread *ambientLightingThread; // advui-inject-ambient-type}m' "$MC"
  echo "fixed ambientLightingThread ODR type mismatch in main.cpp"
fi
if [ -f "$MC" ] && ! grep -q 'advui/AdvUI.h" // advui-inject' "$MC"; then
  perl -0pi -e 's{#include "main\.h"\n}{#include "main.h"\n#include "advui/AdvUI.h" // advui-inject\n}' "$MC"
  perl -0pi -e 's{(\n[ \t]*setupModules\(\);\n)}{$1    advui::advuiSetup(); // advui-inject\n}' "$MC"
  perl -0pi -e 's{(\n[ \t]*consoleInit\(\); // Set serial baud rate and init our mesh console\n)}{$1#if defined(ARDUINO_USB_CDC_ON_BOOT) && ARDUINO_USB_CDC_ON_BOOT\n    Serial.setTxTimeoutMs(1); // advui-inject: minimum safe HWCDC timeout when the host is not draining\n#endif\n}' "$MC"
  echo "injected advui hooks into main.cpp"
fi

# SerialConsole.cpp: in the ADVUI_SCREENSHOT dev build the remote-debug driver owns serial
#     input (keys/screenshots); the stock console polls-and-drains the same
#     port whenever USB is plugged and would eat those bytes. Dead code in
#     release builds (the flag is never set there).
SC="$FW/src/SerialConsole.cpp"
SC_H="$FW/src/SerialConsole.h"
if [ -f "$SC" ] && ! grep -q 'the screenshot build reads serial itself' "$SC"; then
  perl -0pi -e 's{(int32_t SerialConsole::runOnce\(\)\n\{\n)}{$1#ifdef ADVUI_SCREENSHOT\n    return 250; // advui-inject: the screenshot build reads serial itself\n#endif\n}' "$SC"
  echo "injected advui screenshot hook into SerialConsole.cpp"
fi

# AudioThread.h: optional RTTTL/SAM alerts must fail soft when the fragmented
# no-PSRAM heap cannot allocate a source/generator. The pinned implementation
# uses throwing new and leaves partial playback state alive after begin() fails.
AUDIO_THREAD="$FW/src/AudioThread.h"
if [ -f "$AUDIO_THREAD" ] && ! grep -q 'new (std::nothrow) AudioGeneratorRTTTL' "$AUDIO_THREAD"; then
  git -C "$FW" apply "$ROOT/overlay/patches/audio-rtttl-failsoft.patch"
  echo "injected fail-soft audio allocations into AudioThread.h"
fi
grep -q 'new (std::nothrow) AudioGeneratorRTTTL' "$AUDIO_THREAD"
grep -q 'new (std::nothrow) AudioOutputI2S' "$AUDIO_THREAD"
grep -q 'constructors/begin() may still throw' "$AUDIO_THREAD"

# SafeFile.cpp: Arduino FS builds File handles with throwing shared_ptr
# allocations. A low/fragmented heap must defer the persistence transaction,
# retaining the previous atomic file, instead of rebooting the whole node.
SAFE_FILE="$FW/src/SafeFile.cpp"
if [ -f "$SAFE_FILE" ] && ! grep -q 'SafeFile open deferred: heap allocation failed' "$SAFE_FILE"; then
  git -C "$FW" apply "$ROOT/overlay/patches/safefile-oom-failsoft.patch"
  echo "injected fail-soft SafeFile allocation handling"
fi
grep -q 'SafeFile open deferred: heap allocation failed' "$SAFE_FILE"
grep -q 'SafeFile close deferred: heap allocation failed' "$SAFE_FILE"

# NodeDB must propagate the verified SafeFile close/rename result. Encoding into
# an invalid or uncommittable File is not a successful persistence operation.
SAVE_PROTO_DB="$FW/src/mesh/NodeDB.cpp"
if [ -f "$SAVE_PROTO_DB" ] && ! grep -q 'advui-inject-safe-write-result' "$SAVE_PROTO_DB"; then
  git -C "$FW" apply "$ROOT/overlay/patches/saveproto-commit-result.patch"
  echo "injected verified saveProto commit result"
fi
test "$(grep -c 'advui-inject-safe-write-result' "$SAVE_PROTO_DB" || true)" -eq 1

# RadioLibInterface.cpp: USB HIL is an isolated test transport, never a radio
# transmitter. USERPREFS_LORA_TX_DISABLED makes the ordinary boot config
# receive-only, while this final interface guard is immutable even if a bonded
# phone or network admin client changes tx_enabled during the run.
RI="$FW/src/mesh/RadioLibInterface.cpp"
if [ -f "$RI" ] && ! grep -q 'advui-inject-hil-rx-only' "$RI"; then
  perl -0pi -e 's{(ErrorCode RadioLibInterface::send\(meshtastic_MeshPacket \*p\)\n\{\n)}{$1#ifdef ADVUI_HIL
    // advui-inject-hil-rx-only: release HIL consumes USB-injected FromRadio
    // fixtures and must never put any packet on the live mesh.
    packetPool.release(p);
    return ERRNO_DISABLED;
#endif
}' "$RI"
  grep -q 'advui-inject-hil-rx-only' "$RI"
  echo "injected immutable HIL radio-TX guard into RadioLibInterface.cpp"
fi

# Router.cpp: RadioLibInterface is the final LoRa hop, but Router fans packets
# out to MQTT and UDP before it calls the radio interface. HIL may boot with a
# saved production broker/channel configuration, so guard every network fanout
# at its source as well. Production builds compile the exact upstream path.
ROUTER="$FW/src/mesh/Router.cpp"
if [ -f "$ROUTER" ]; then
  router_hil_guards=$(grep -c 'advui-inject-hil-network-silence' "$ROUTER" || true)
  if [ "$router_hil_guards" -eq 0 ]; then
    perl -0pi -e 's{#if !MESHTASTIC_EXCLUDE_MQTT\n(        // Only publish to MQTT if[^\n]*)}{#if !MESHTASTIC_EXCLUDE_MQTT \&\& !defined(ADVUI_HIL) // advui-inject-hil-network-silence\n$1}' "$ROUTER"
    perl -0pi -e 's{#if HAS_UDP_MULTICAST\n(    if \(udpHandler \&\& config\.network\.enabled_protocols)}{#if HAS_UDP_MULTICAST \&\& !defined(ADVUI_HIL) // advui-inject-hil-network-silence\n$1}' "$ROUTER"
    perl -0pi -e 's{#if !MESHTASTIC_EXCLUDE_MQTT\n(        if \(p_encrypted == nullptr\))}{#if !MESHTASTIC_EXCLUDE_MQTT \&\& !defined(ADVUI_HIL) // advui-inject-hil-network-silence\n$1}' "$ROUTER"
    echo "injected immutable HIL MQTT/UDP guards into Router.cpp"
  fi
  test "$(grep -c 'advui-inject-hil-network-silence' "$ROUTER" || true)" -eq 3
fi

# Do not even construct autonomous MQTT or WiFi threads in HIL. This closes
# map reports, proxy traffic and direct debug publication outside Router while
# leaving the production build preprocessor path identical to upstream.
if [ -f "$MC" ] && ! grep -q 'advui-inject-hil-no-mqtt-init' "$MC"; then
  perl -0pi -e 's{#if !MESHTASTIC_EXCLUDE_MQTT\n(    mqttInit\(\);)}{#if !MESHTASTIC_EXCLUDE_MQTT \&\& !defined(ADVUI_HIL) // advui-inject-hil-no-mqtt-init\n$1}' "$MC"
  echo "injected immutable HIL MQTT-init guard into main.cpp"
fi
test "$(grep -c 'advui-inject-hil-no-mqtt-init' "$MC" || true)" -eq 1
if [ -f "$MC" ] && ! grep -q 'advui-inject-hil-no-wifi-init' "$MC"; then
  perl -0pi -e 's{#if HAS_WIFI\n(    initWifi\(\);)}{#if HAS_WIFI \&\& !defined(ADVUI_HIL) // advui-inject-hil-no-wifi-init\n$1}' "$MC"
  echo "injected immutable HIL WiFi-init guard into main.cpp"
fi
test "$(grep -c 'advui-inject-hil-no-wifi-init' "$MC" || true)" -eq 1

# The stock Meshtastic PhoneAPI is a BLE peripheral independent of ADV's
# companion-central transport. A bonded phone could otherwise connect during
# HIL, read live config/NodeDB and send persistent admin writes. Keep the whole
# stock BLE enable path inert in HIL before NimBLE is constructed or advertises;
# production builds compile the upstream body unchanged.
ESP32_MAIN="$FW/src/platform/esp32/main-esp32.cpp"
if [ -f "$ESP32_MAIN" ] && ! grep -q 'advui-inject-hil-no-stock-ble' "$ESP32_MAIN"; then
  perl -0pi -e 's{(void setBluetoothEnable\(bool enable\)\n\{\n)}{$1#ifdef ADVUI_HIL
    (void)enable;
    return; // advui-inject-hil-no-stock-ble: no BLE advertising or PhoneAPI in release HIL
#endif
}' "$ESP32_MAIN"
  echo "injected immutable HIL stock-BLE guard into main-esp32.cpp"
fi
test "$(grep -c 'advui-inject-hil-no-stock-ble' "$ESP32_MAIN" || true)" -eq 1

# StreamAPI + ServerAPI: a full 150-node config dump can fill the TCP send
# window. The pinned implementation keeps dequeuing frames even after a short
# write and never returns to loop(), eventually tripping the task watchdog.
# Slice the cooperative drain. A follow-up patch retains partial frames and
# uses zero-wait lwIP writes on ESP32 so backpressure cannot corrupt a frame or
# starve loop() long enough to trip the watchdog.
STREAM_API="$FW/src/mesh/StreamAPI.cpp"
STREAM_API_H="$FW/src/mesh/StreamAPI.h"
SERVER_API="$FW/src/mesh/api/ServerAPI.cpp"
SERVER_API_H="$FW/src/mesh/api/ServerAPI.h"
if [ -f "$STREAM_API" ] && [ -f "$STREAM_API_H" ] && \
   [ -f "$SERVER_API" ] && [ -f "$SERVER_API_H" ] && \
   ! grep -q 'advui-inject-bounded-stream-writes' "$STREAM_API_H"; then
  git -C "$FW" apply "$ROOT/overlay/patches/streamapi-bounded-writes.patch"
  echo "injected bounded StreamAPI writes and TCP short-write guard"
fi
test "$(grep -c 'advui-inject-bounded-stream-writes' "$STREAM_API_H" || true)" -eq 1

FRAME_WRITER="$FW/src/mesh/StreamFrameWriter.cpp"
FRAME_WRITER_H="$FW/src/mesh/StreamFrameWriter.h"
USB_SESSION_STREAM="$FW/src/mesh/UsbSessionStream.h"
stream_retained_tracked_ready() {
  grep -q 'StreamFrameWriter frameWriter' "$SC_H" &&
    grep -q 'virtual bool finishPendingFrame' "$STREAM_API_H" &&
    grep -q 'StreamFrameWriter frameWriter' "$FW/src/mesh/api/WiFiServerAPI.h" &&
    grep -q 'MSG_DONTWAIT' "$FW/src/mesh/api/WiFiServerAPI.cpp" &&
    grep -q 'resetStreamInput' "$SC"
}
stream_retained_generated_ready() {
  test -f "$FRAME_WRITER" && test -f "$FRAME_WRITER_H" && test -f "$USB_SESSION_STREAM" &&
    grep -q 'HWCDC::isConnected()' "$USB_SESSION_STREAM"
}
stream_retained_ready() {
  stream_retained_tracked_ready && stream_retained_generated_ready
}
if ! stream_retained_ready; then
  # actions/checkout resets tracked submodule files but older self-hosted work
  # directories can retain these three generated files. Remove only that known
  # incomplete patch residue, then apply the exact reviewed patch normally.
  if ! stream_retained_tracked_ready; then
    rm -f -- "$FRAME_WRITER" "$FRAME_WRITER_H" "$USB_SESSION_STREAM"
    git -C "$FW" apply "$ROOT/overlay/patches/streamapi-retained-nonblocking-writes.patch"
  else
    # The inverse mixed state is also recoverable: tracked hunks are complete,
    # but a cleanup removed one or more generated headers/sources.
    rm -f -- "$FRAME_WRITER" "$FRAME_WRITER_H" "$USB_SESSION_STREAM"
    git -C "$FW" apply \
      --include=src/mesh/StreamFrameWriter.cpp \
      --include=src/mesh/StreamFrameWriter.h \
      --include=src/mesh/UsbSessionStream.h \
      "$ROOT/overlay/patches/streamapi-retained-nonblocking-writes.patch"
  fi
  echo "injected retained non-blocking StreamAPI transport writes"
fi
stream_retained_ready
grep -q 'delegate.availableForWrite()' "$FW/src/mesh/UsbSessionStream.h"
grep -q 'resetStreamInput' "$SC"

# Per-connection PhoneAPI objects and the WiFi listener are normally small, but
# both constructors allocate thread/stream state from the fragmented internal
# heap. Refuse that connection or listener start instead of allowing bad_alloc
# to escape into std::terminate and reboot an otherwise healthy mesh node.
WIFI_SERVER_API="$FW/src/mesh/api/WiFiServerAPI.cpp"
if [ -f "$SERVER_API" ] && [ -f "$WIFI_SERVER_API" ] && \
   ! grep -q 'advui-inject-serverapi-oom-failsoft' "$SERVER_API"; then
  git -C "$FW" apply "$ROOT/overlay/patches/serverapi-oom-failsoft.patch"
  echo "injected fail-soft PhoneAPI connection allocation"
fi
test "$(grep -c 'advui-inject-serverapi-oom-failsoft' "$SERVER_API" || true)" -eq 1
test "$(grep -c 'advui-inject-wifi-listener-oom-failsoft' "$WIFI_SERVER_API" || true)" -eq 1

# PhoneAPI.cpp/.h: upstream 2.7 keeps prefetched NodeInfo records in a
# std::deque. Every time the deque needs another 308-byte block it calls the
# throwing operator new; on an ESP32 without enough contiguous internal heap,
# the unwind path ends in abort() and a reboot. ADV's UI plus a real 150-node
# database reproduced that failure during a WiFi PhoneAPI config dump. Reuse
# the existing single-record staging slot: no extra resident payload and no
# allocation while the heap is fragmented. The patch is intentionally pinned to the
# reviewed 2.7.26 layout and fails closed when an engine update changes it.
PHONE_API="$FW/src/mesh/PhoneAPI.cpp"
PHONE_API_H="$FW/src/mesh/PhoneAPI.h"
if [ -f "$PHONE_API" ] && [ -f "$PHONE_API_H" ] && \
   ! grep -q 'advui-inject-fixed-node-prefetch' "$PHONE_API_H"; then
  git -C "$FW" apply "$ROOT/overlay/patches/phoneapi-fixed-node-prefetch.patch"
  echo "injected allocation-free PhoneAPI node prefetch"
fi
test "$(grep -c 'advui-inject-fixed-node-prefetch' "$PHONE_API" || true)" -eq 1
test "$(grep -c 'advui-inject-fixed-node-prefetch' "$PHONE_API_H" || true)" -eq 1

# Keep config/node dumps away from two unrelated heap hazards: build the file
# manifest only after the node stream has finished, and replace the unbounded
# per-port unordered_map with six fixed rate-limit timestamp slots.
if [ -f "$PHONE_API" ] && [ -f "$PHONE_API_H" ] && \
   ! grep -q 'advui-inject-bounded-phone-memory' "$PHONE_API_H"; then
  git -C "$FW" apply "$ROOT/overlay/patches/phoneapi-bounded-memory.patch"
  echo "injected bounded PhoneAPI manifest and rate-limit storage"
fi
test "$(grep -c 'advui-inject-bounded-phone-memory' "$PHONE_API_H" || true)" -eq 1

# WebServer.cpp + ContentHandler.cpp: drop the HTTPS/TLS server, keep HTTP:80.
# The self-signed RSA-2048 cert plus mbedTLS session state costs tens of KB of
# heap on this no-PSRAM board — the stock code already logs "skipping HTTPS
# processing" under memory pressure, and every local tool talks to :80 anyway.
# Nulling secureServer leans on the stock `if (secureServer)` guards around
# loop()/start(); the handler-registration block (unguarded upstream) is wrapped
# to match, and the cert generator is short-circuited so a clean install never
# spends the RSA-keygen heap spike on a tight heap.
WS="$FW/src/mesh/http/WebServer.cpp"
if [ -f "$WS" ] && ! grep -q 'advui-inject-nohttps' "$WS"; then
  perl -0pi -e 's{secureServer = new HTTPSServer\(cert, 443, MAX_HTTPS_CONNECTIONS\);}{secureServer = nullptr; // advui-inject-nohttps: HTTPS off, keep HTTP:80 -> frees tens of KB heap}' "$WS"
  perl -0pi -e 's{(void createSSLCert\(\)\n\{\n)}{$1    return; // advui-inject-nohttps: HTTPS disabled, skip the RSA-2048 self-signed cert gen\n}' "$WS"
  echo "injected advui no-HTTPS hooks into WebServer.cpp"
fi
CH="$FW/src/mesh/http/ContentHandler.cpp"
if [ -f "$CH" ] && ! grep -q 'advui-inject-nohttps' "$CH"; then
  # @-delimited: the replacement carries C++ braces, which would unbalance s{}{}.
  perl -0pi -e 's@(    secureServer->registerNode\(nodeAPIv1ToRadioOptions\);)@    if (secureServer) { // advui-inject-nohttps: HTTPS server is not created\n$1@' "$CH"
  perl -0pi -e 's@(    secureServer->registerNode\(nodeRoot\); // This has to be last\n)@$1    } // advui-inject-nohttps\n@' "$CH"
  echo "injected advui no-HTTPS guard into ContentHandler.cpp"
fi

# The bundled HTTP server and JSON handlers use throwing STL allocations for
# each accepted request. Under fragmented-heap pressure, retire only the local
# web UI instead of allowing bad_alloc to reboot the mesh node. Limit the
# already-HTTP-only server to the same two concurrent clients as the removed
# HTTPS listener.
if [ -f "$WS" ] && ! grep -q 'advui-inject-webserver-oom-failsoft' "$WS"; then
  git -C "$FW" apply "$ROOT/overlay/patches/webserver-oom-failsoft.patch"
  echo "injected fail-soft HTTP allocation handling"
fi
test "$(grep -c 'advui-inject-webserver-oom-failsoft' "$WS" || true)" -eq 1

# NodeDB.cpp: saveNodeDatabaseToDisk() stages the four satellite maps into
# on-disk vectors with reserve() calls that each want a contiguous multi-KB
# block. On this no-PSRAM board under a busy mesh the heap can be ground low
# enough that std::bad_alloc escapes to std::terminate and reboots the node
# mid-operation — which, when it lands during a PhoneAPI config dump (a save is
# triggered by every incoming NodeInfo), is exactly what stops the dump from
# ever reaching config_complete_id. Wrap the staging in a bad_alloc catch that
# defers the save (returns true, not false — false would send saveToDisk() down
# its retry/fsFormat path). Applied as a patch: it spans two hunks.
ND="$FW/src/mesh/NodeDB.cpp"
if [ -f "$ND" ] && ! grep -q 'advui-inject-hil-preserve-nodedb' "$ND"; then
  git -C "$FW" apply "$ROOT/overlay/patches/nodedb-hil-preserve-cache.patch"
  echo "injected immutable HIL NodeDB persistence guard"
fi
test "$(grep -c 'advui-inject-hil-preserve-nodedb' "$ND" || true)" -eq 1
NDH="$FW/src/mesh/NodeDB.h"
if [ -f "$NDH" ] && ! grep -q 'advui-inject-hil-isolated-nodedb' "$NDH"; then
  git -C "$FW" apply "$ROOT/overlay/patches/nodedb-hil-isolated-cache.patch"
  echo "isolated the HIL NodeDB cache path"
fi
test "$(grep -c 'advui-inject-hil-isolated-nodedb' "$NDH" || true)" -eq 1
if [ -f "$ND" ] && ! grep -q 'advui-inject-oomsave' "$ND"; then
  # The 2.8 NodeDB projects four satellite maps into temporary protobuf
  # vectors before saving. The 2.7 release line stores a single monolithic
  # node vector and has no such staging allocation, so this exact OOM path
  # does not exist there. Key the patch to the vulnerable structure rather
  # than to a firmware version string so both supported layouts stay safe.
  if grep -q 'nodeDatabase.positions.reserve' "$ND"; then
    git -C "$FW" apply "$ROOT/overlay/patches/nodedb-oom-save.patch"
    echo "injected advui oom-save patch into NodeDB.cpp"
  else
    echo "skipped advui oom-save patch: NodeDB has no satellite staging vectors"
  fi
fi

# A Cardputer that has already run the 2.8 development line can carry a v25
# nodes.proto. Meshtastic 2.7 normally accepts every version >=24, but its v24
# NodeInfoLite schema cannot decode v25's flattened identity fields. Discard
# only the rebuildable node cache; identity, channels and radio configuration
# remain intact. Newer firmware has its own explicit v24 migration and must not
# receive this downgrade-only guard.
if [ -f "$ND" ] && [ -f "$NDH" ] && ! grep -q 'advui-inject-forward-nodedb' "$ND"; then
  if grep -q '^#define DEVICESTATE_CUR_VER 24$' "$NDH" && \
     grep -q 'if (nodeDatabase.version < DEVICESTATE_MIN_VER)' "$ND"; then
    git -C "$FW" apply "$ROOT/overlay/patches/nodedb-forward-version.patch"
    echo "injected forward-version guard into NodeDB.cpp"
  fi
fi

# NodeDB.cpp: nanopb decodes the saved vector with push_back. Without an exact
# reservation, a full 150-node database grows to capacity 256 and permanently
# strands roughly 20 KiB of internal heap. Reserve once while boot still has a
# large contiguous block; the patch is pinned after the v24 forward guard above.
if [ -f "$ND" ] && ! grep -q 'advui-inject-nodedb-reserve' "$ND"; then
  git -C "$FW" apply "$ROOT/overlay/patches/nodedb-reserve-before-decode.patch"
  echo "reserved exact NodeDB capacity before decode"
fi
test "$(grep -c 'advui-inject-nodedb-reserve' "$ND" || true)" -eq 1

# ADV sends need the synchronous queue-admission result. Existing callers may
# ignore the returned ErrorCode, so widening the API is source-compatible.
MS="$FW/src/mesh/MeshService.cpp"
MSH="$FW/src/mesh/MeshService.h"
if grep -q '^void MeshService::sendToMesh' "$MS"; then
  git -C "$FW" apply "$ROOT/overlay/patches/meshservice-send-result.patch"
  echo "injected MeshService send result"
fi
grep -q '^ErrorCode MeshService::sendToMesh' "$MS"
grep -q '^    ErrorCode sendToMesh' "$MSH"

echo "overlay synced into $FW"
